### ISSUE TITLE
Localization: English

### ISSUE THREAD

**Issue by ljukas** [studentorkesterfestivalen/sof-webapp#38]
Make orchestra signup and information pages viewable in english.

**Comment by patriksletmo** [comment]
**Remaining pages**
- [x] Information
- [ ] Creation (missing description for dormitory)
- [ ] Registration (missing translation for dynamically generated content)
- [ ] Show orchestra
- [ ] Show signup

**Comment by patriksletmo** [comment]
[I was promised a progress indicator from this task list](https://guides.github.com/features/mastering-markdown/) but that turned out to be a lie.
