### ISSUE TITLE
Minor: Dormitory shows in Summary even if orchestra has chosen no dormitory

### ISSUE THREAD

**Issue by ljukas** [studentorkesterfestivalen/sof-webapp#51]

**Comment by patriksletmo** [comment]
**Suggestion:** Provide orchestra dormitory preference as a response when verifying the orchestra code and update the UI accordingly. Default to no dormitory if the orchestra code is invalid.

Could I get your input on this, @ljukas?

**Comment by ljukas** [comment]
Default to no, and when an orchestra code checks out to be valid, query for the orchestras choice and update the summary accordingly.

**Comment by patriksletmo** [comment]
Closed in pull request #55.
