### ISSUE TITLE
Login: Logging in with LiU-ID sometimes create multiple accounts for the same student

### ISSUE THREAD

**Issue by patriksletmo** [studentorkesterfestivalen/sof-webapp#53]
By entering a LiU-ID in CAS with a different letter casing combination (eg. aBcde123 instead of abcde123) the system will create a completely new user.

**Comment by patriksletmo** [comment]
Fix available in [sof-dbapp#16](https://github.com/studentorkesterfestivalen/sof-dbapp/pull/16).

**Comment by ljukas** [comment]
CLosed, new issue for a more permanent fix is available, see #62
